//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILR1819.DataStore.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM25_FM35_Learner_Period
    {
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public int Period { get; set; }
        public Nullable<decimal> LnrOnProgPay { get; set; }
    
        public virtual FM25_FM35_global FM25_FM35_global { get; set; }
        public virtual FM25_Learner FM25_Learner { get; set; }
    }
}
