//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.DC.ILR1819.DataStore.EF.Valid
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearnerHE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LearnerHE()
        {
            this.LearnerHEFinancialSupports = new HashSet<LearnerHEFinancialSupport>();
        }
    
        public int UKPRN { get; set; }
        public string LearnRefNumber { get; set; }
        public string UCASPERID { get; set; }
        public Nullable<int> TTACCOM { get; set; }
    
        public virtual Learner Learner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LearnerHEFinancialSupport> LearnerHEFinancialSupports { get; set; }
    }
}
